DROP TABLE IF EXISTS twoway_synonym;

CREATE TABLE twoway_synonym (
    uuid varchar(36) UNIQUE NOT NULL,
    synonym varchar(55) UNIQUE NOT NULL,
    group_id integer GENERATED BY DEFAULT AS IDENTITY
);