@startuml

interface BrandGetter {
    + query(tokens: List<String>): List<Integer>
}

interface Filterable {
    + filter(tokens: ArrayList<String>): ArrayList<String>
}

interface IndexingModule {
    + queryIndex(tokens: List<String>): List<T>
}


interface SearchModule {
    + search(query: String): SearchResult
    + getDelimiters(): String[]
    + getIgnoredCharacters(): Character[]
    + addDelimiter(delimiter: String)
    + addIgnoredCharacter(c: Character)
    + removeDelimiter(delimiter: String)
    + removeIgnoredCharacter(c: Character)
    + SearchHits search(query: String)
}

class ReplaceForbbidenChars {
    + removeForbiddenChars(toSort: String): String
}

class SearchModuleImpl implements SearchModule {
    - indexingModules: Set<IndexingModule<?>>
    - filteringModule: Set<Filterable>

    - addIndexingModule(index: T): void
    - removeIndexingmModule(index: T): void
    + queryIndexOfType(clazz: Class<T>, tokens: List<String>): List<T>
    + search(query: String): SearchHits
    - tokenize(mystring): String[]
    - saveSettingsToDB()
    - readSettingsFromDB()
}

class SearchModuleUtils {
    + {static}convertDelimitersToRegex(stringList: List<String>): String
    - {static}addDelimiterToStringBuilder(sb: StringBuilder, i: int, (stringList: List<String>): void
}

class DelimiterSettings {
    - delimiters: List<String>
    + getDelimiters(): List<String>
    + addDelimiters(String): void
    + removeDelimiter(String): boolean
}

class TokenFiltration {
    +filter(tokens: ArrayList<String>): ArrayList<String>
}

class Tokenization {
    - searchModuleUtils: SearchModuleUtils
    - ss: SearchSettings
    - stringList: List<String>
    +tokenize(s: String): list<String>
}

class DBConnection {
    - url: String
    - user: String
    - password: String
    - {static}conn: Connection
    - {static} dbConnection: DBConnection

    - loadConfig(): void
    + {static} getConnection(): Connection

}


Tokenization -> SearchModuleUtils
Tokenization --> DelimiterSettings
SearchHits <- SearchModule
Filterable <- SearchModuleImpl
SearchModuleImpl --> DBConnection
SearchModuleImpl -> DelimiterSettings



@enduml