@startuml
'https://plantuml.com/sequence-diagram
package searchmodule {
  package infrastructure{
  package interfaces{
    class BrandGetter
    class Filterable
    class IndexingModule
    class SearchModule
}
class DelimiterSettings
class IllegalChars
class ReplaceForbiddenChars
class SearchLog
class SearchLogger
class SearchModuleImpl
class SearchModuleUtils
class SEM1InfrastructureAdministrativeGUIController
class Tokenizer
@enduml