@startuml
title "SEM  - Sequence Diagram"


participant "SOM-1"
participant "SEM-1 (US)"
participant "SEM-2"
participant "SEM-3"
participant "SEM-4"
participant "BIM-4"
participant "CMS-4"

"SOM-1" -> "SEM-1 (US)" : search(searchString)

activate "SEM-1 (US)"
"SEM-1 (US)" -> "SEM-1 (US)" : removeIllegalChars()
"SEM-1 (US)" -> "SEM-1 (US)" : tokenize()


"SEM-1 (US)" -> "SEM-3": filter(tokens)
activate "SEM-3"
"SEM-1 (US)" <-- "SEM-3" : filtered tokens
deactivate "SEM-3"

"SEM-1 (US)" -> "SEM-4":filter(tokens)
activate "SEM-4"
"SEM-1 (US)" <-- "SEM-4" : filtered tokens
deactivate "SEM-4"

"SEM-1 (US)" -> "BIM-4":filter(tokens)
activate "BIM-4"
"SEM-1 (US)" <-- "BIM-4" : filtered tokens
deactivate "BIM-4"

"SEM-1 (US)" -> "CMS-4":filter(tokens)
activate "CMS-4"
"SEM-1 (US)" <-- "CMS-4" : filtered tokens
deactivate "CMS-4"

participant "CMS-2"
participant "PIM-2"
participant "BIM-2"

"SEM-1 (US)" -> "CMS-2": search(tokens)
activate "CMS-2"
"SEM-1 (US)" <-- "CMS-2" : hits
deactivate "CMS-2"

"SEM-1 (US)" -> "PIM-2": search(tokens)
activate "PIM-2"
"SEM-1 (US)" <-- "PIM-2" : hits
deactivate "PIM-2"

"SEM-1 (US)" -> "BIM-2": search(tokens)
activate "BIM-2"
"SEM-1 (US)" <-- "BIM-2" : hits
deactivate "BIM-2"

"SOM-1" <-- "SEM-1 (US)" : search(searchString)
deactivate "SEM-1 (US)"

@enduml