name: Java system test

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Set up postgres credentials
        run: |
          touch config.properties
          echo db_url=jdbc:postgresql://localhost:5432/postgres_db >> config.properties
          echo db_user=postgres_user >> config.properties
          echo db_password=postgres_password >> config.properties
        shell: bash
      - name: Run migrations
        run: mvn compile exec:java -Dexec.mainClass="dk.sdu.se_f22.sharedlibrary.db.DBMigrationFresh"
      - name: Verify with maven
        run: mvn --batch-mode --update-snapshots verify